SELECT TBISLER.ISADI, TBIMALATKALS.POZNO, TBIMALATKALS.ACIKLAMA, TBIMALATKALS.BIRIMFIYAT, TBBIRIMS.BIRIMADI, TBPARABIRIMS.PARABIRIMI, TBIMALATKALS.SOZLESMEMIKTARI
FROM TBPARABIRIMS INNER JOIN (TBISLER INNER JOIN (TBBIRIMS INNER JOIN TBIMALATKALS ON TBBIRIMS.Kimlik = TBIMALATKALS.BIRIM) ON TBISLER.Kimlik = TBIMALATKALS.ISKODU) ON TBPARABIRIMS.Kimlik = TBIMALATKALS.PARABIRIMI
WHERE (((TBPARABIRIMS.PARABIRIMI)=[paraBirim]) AND ((IIf(IsNull([FORMS].[FRMAIN].[Açılan_Kutu62]),'*',[FORMS].[FRMAIN].[Açılan_Kutu62]=[TBIMALATKALS].[ISKODU]))<>False));

