SELECT TBKESINTI.Kimlik, F1.FIRMAADI AS VERILECEKFIRMA, F2.FIRMAADI AS KESILECEKFIRMA, TBKESINTITUR.TURADI, TBKESINTI.MIKTAR, TBBIRIMS.BIRIMADI, TBKESINTI.BIRIMFIYAT, TBKESINTI.KDV, TBKESINTI.VERITARIHI, [BIRIMFIYAT]*[MIKTAR] AS TUTAR, [TUTAR]*(([KDV]/100)+1) AS KDVLÝTUTAR, TBKESINTI.DURUM
FROM TBKESINTITUR INNER JOIN (TBFIRMA AS F2 INNER JOIN (TBBIRIMS INNER JOIN (TBFIRMA AS F1 INNER JOIN TBKESINTI ON F1.Kimlik = TBKESINTI.VERILECEKFIRMA) ON TBBIRIMS.Kimlik = TBKESINTI.BIRIM) ON F2.Kimlik = TBKESINTI.KESILECEKFIRMA) ON TBKESINTITUR.Kimlik = TBKESINTI.KESINTITURU
ORDER BY TBKESINTI.Kimlik DESC;

